name: MSBuild

on:
  push:
    branches: [ "v2","ci" ]
  pull_request:
    branches: [ "v2","ci" ]
    

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Install VCPKG packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: vcpkg install cpp-httplib:x86-windows detours:x86-windows pystring:x86-windows nlohmann-json:x86-windows kubazip:x86-windows neargye-semver:x86-windows ; vcpkg integrate install

    - name: Install NPM packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cd ./src/js-framework ; npm i

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild .\BetterNCMII.sln -p:Platform="x86" -p:Configuration=Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: BetterNCMII
        path: ${{ github.workspace }}/Release/BetterNCMII.dll
        
    - uses: "marvinpinto/action-automatic-releases@latest"
      name: Upload to Github Release
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "dev-nightly"
        prerelease: true
        title: "Latest Test Release"
        files: ${{ github.workspace }}/Release/BetterNCMII.dll
